@Restaurants.Api_HostAddress = https://localhost:7117
@Token = CfDJ8AtTUCxZepRNtQjtfJx2wLl0zBtqRIhjy4hcNv1H-Pz1Ld6xSflb2LRdoONKz5RraNOWm4cxb8f8PkQL9RnlBF5zw2HEYjzYcnx_Qro4V84kmQjqN2a72lw4yYJ_24O9UIV1udTXOJTHe0yWFQr9Sx7qpknbsP8oR2dYMqcvotbTUVo_pqfefHSamz3AY8qqeIXwHBvkaxvst8eJyXGYJ8AZiIZQ4Vy_bbAtwvIdN9KeTQ1yl0fanINK6TUBAGiBmMB5Jq45oUBxqXga0lxMpk4RXtjDcjG6yYSNZu-mPxbOepmEOkEkw6dPrahae8Up4826TFnCr8zw_8ZKt3u27WvK0HWworcDRKUmMvSNgGdsOW3qIvqNA4RJAnISu5eew5L_ZgDRDCoKYGTZskgpwnPhz2lR-SKi7Etg4rzYoVc_ypLT-VTDJM6BmiGagRnZpmLjMi40teJH9TtuynPDpy5NPLHNu_CLjKYQG6EsAphV9-dYMh0ISPFrOhzU2_fw312CZ2QJ8YYlffuJRxHm5LFvy6oiw25Ky7XPpU8jVfma8iyrvbPBYIiUtpVS-gUf5KCg4MNBwyR885Ix0bTeVLgVp--VCzckWFW6o6Xw61IDJZ-uD4AzyWgb-4Xp2tIQl0ZygA7lU0ryxMf_-sltRtFavqGJ5CEptQTcSnjV2P6Fx2VvW1GcGX00Y7Qx4mwj2TqDzBL4jfQ2b-3CrEgUyj4W4YL-zM1HBT6yKQi-C6M4MjJs3vEDeupT8qYTQ24epYcC3w878aPAqnK3SA70vJIRZQSJbmtdWVENoBsPbi_77XquhWMYbBsW46Etiq4j6KGe8Yet2pqy4yJ4_P_ZuJiZ0_HXSg8fECvUNWoukCTog9LWj6XjTGxbG5Rfg_KMmQ
GET {{Restaurants.Api_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}
###

GET {{Restaurants.Api_HostAddress}}/api/restaurants/8
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "Name": "Owner test",
  "Description": "A culinary experience like no other",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "01248361969",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-551"
}


###



DELETE {{Restaurants.Api_HostAddress}}/api/restaurants/8
Authorization: Bearer {{Token}}
###

PATCH {{Restaurants.Api_HostAddress}}/api/restaurants/8
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "Name": "hello",
  "Description": "Hello Tester",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "01248361969",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-551"
}
###


POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "owner@test.com",
  "password": "Password1!"
}
###
GET {{Restaurants.Api_HostAddress}}/api/restaurant/1/menuCategories
Authorization: Bearer {{Token}}
###
GET {{Restaurants.Api_HostAddress}}/api/restaurant/2/menuCategories/9
###
@restaurantId=0
DELETE {{Restaurants.Api_HostAddress}}/api/restaurant/2/menuCategories/3

###

POST {{Restaurants.Api_HostAddress}}/api/restaurant/2/menuCategories
Content-Type: application/json

{
 "name": "tester"
}

###

@dishId=0
@menuCategoryId=0
GET {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes/7

###

POST {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "tester",
    "description": "tester",
    "price": 10.00,
    "kiloCalories": 110
}

###

PATCH {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes/7
Authorization: Bearer {{Token}}
Content-Type: application/json

{  
   "name": "hhhhh",
    "description": "tester",
    "price": 10.00,
    "kiloCalories": 110
}

###

DELETE {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes/7
Authorization: Bearer {{Token}}
###

PATCH {{Restaurants.Api_HostAddress}}/api/identity/user
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "nationality": "Egyptian",
  "DateOfBirth": "2002-02-02" 
}

###
