@Restaurants.Api_HostAddress = https://localhost:7117


GET {{Restaurants.Api_HostAddress}}/api/restaurants

###


GET {{Restaurants.Api_HostAddress}}/api/restaurants/5

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "test2",
  "Description": "A culinary experience like no other",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "01248361969",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-551"
}


###



DELETE {{Restaurants.Api_HostAddress}}/api/restaurants/{id}

###

PATCH {{Restaurants.Api_HostAddress}}/api/restaurants/5
Content-Type: application/json

{
  "Name": "test4",
  "Description": "Hello Tester",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "01248361969",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-551"
}
###

GET {{Restaurants.Api_HostAddress}}/api/dishes

###

@id=0
GET {{Restaurants.Api_HostAddress}}/api/restaurants/{{id}}

###
