@Restaurants.Api_HostAddress = https://localhost:7117
@Token = CfDJ8AtTUCxZepRNtQjtfJx2wLkTM8va_6RKrCbzoqQWKWzL8LSB6SeXO1wZAFDW6FxxbYSZRidR1YXvCUDg6KC4g0O4GvNsLVzAUt2OOyddb0R-BoYCiZg3scoNi3wft-0D3XZWvSH97vcQECtdadXpi4WkCeDz-wO39WFoA4d93acOFOTuw5AOG7OP927nQCFtXoSqDcZMM1iy6ndzolE5atntJU-BGu5QR6TTvXPBrAY7KJbNIDaimLvy6kqjocdvQOuPh_cQuZelLR-63R0JSnn8CF-2URfLTu6mN7gekY6T39zVhT1PYjbPXrq89Und5EUNE-xDU8dVHnSUOZED2aGEV4RdpqMxD6FZB8F69Gis5lElKiKYqCZpBcSaGQMboaT5AVZjAOPe0m_9KC3iq-iVUfS6lKvdOb9jsrBOXOeYS07EkjGBxuurm4w4me5Yjif9pWomKMNirb-SBKq9pQi3aVX0lYhlbVfiPfm1r254lRUctoRLIhba4i_7aYb4gVIoVTT2tGylc0Mg_BdWOZpTtsMhzCjYt5VoOpvbXFJLZrbj8EaO6o9r2wXveHETsxx9QP0rKIXswtwW1MhYTF20NC8sYCnhmTrqZZZmwp_DYvGo6YUSwzLrt4oTKhlpf5zVB7VYx1Wt7qVhSwBvNBhXk455cvzOpMlghHT-KdsQFOQWbskIhPFFQsReGR5pJKczLgNS5PH7dXijcNiys4z4ZJeLM1DzReBwWc9K041zxHKNOTD0nvaV0hIv7Fry3EQLVJqiUJsULI_Tl-vjC9vHpuzB6IYpmwT05BBaqtBH
GET {{Restaurants.Api_HostAddress}}/api/restaurants
###

GET {{Restaurants.Api_HostAddress}}/api/restaurants/6
Authorization: Bearer {{Token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "Name": "test2",
  "Description": "A culinary experience like no other",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "01248361969",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-551"
}


###



DELETE {{Restaurants.Api_HostAddress}}/api/restaurants/{id}

###

PATCH {{Restaurants.Api_HostAddress}}/api/restaurants/5
Content-Type: application/json

{
  "Name": "test4",
  "Description": "Hello Tester",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "01248361969",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-551"
}
###

GET {{Restaurants.Api_HostAddress}}/api/dishes

###

@id=0
GET {{Restaurants.Api_HostAddress}}/api/restaurants/{{id}}



###

POST {{Restaurants.Api_HostAddress}}/api/restaurant/2/dishe
Content-Type: application/json

{
    "name": "Big Tasty",
    "description": "Sandwich fried Chickin",
    "price": 11,
    "kilocalories":222

}

###

GET {{Restaurants.Api_HostAddress}}/api/restaurant/2/dishes

###

@restaurantId=0
@dishId=0

GET {{Restaurants.Api_HostAddress}}/api/restaurant/2/dishes/35

###

DELETE {{Restaurants.Api_HostAddress}}/api/restaurant/2/dishes

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "tester@test.com",
  "password": "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "tester@test.com",
  "password": "Password1!"
}
###
GET {{Restaurants.Api_HostAddress}}/api/menucategories/1

###

GET {{Restaurants.Api_HostAddress}}/api/restaurant/2/menuCategories

###

@menuCategoryId=0
GET {{Restaurants.Api_HostAddress}}/api/restaurant/1/menuCategories/1

###

GET {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes

###

GET {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes/6

###

POST {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes
Content-Type: application/json

{

  "name": "test",
  "description": "tester",
  "price": 10,
  "kiloCalories": 110


}

###

DELETE {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes/4
###

PATCH {{Restaurants.Api_HostAddress}}/api/restaurants/1/menuCategories/1/dishes/4
Content-Type: application/json
{
  
  "name": "test025",
  "description": "tester2222",
  "price": 10.00,
  "kiloCalories": 1120

}
###

